![Numbers](images/numpy/numbers.jpg)

Photo by [Nick Hillier](https://unsplash.com/photos/yD5rv8_WzxA?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText) on [Unsplash](https://unsplash.com/search/photos/numbers?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText)

In [183]:
from IPython.display import HTML
from pathlib import Path

css_rules = Path('custom.css').read_text()
HTML('<style>' + css_rules + '</style>')

# Motivación

En su [definición](http://www.numpy.org/#numpy) de la página oficial de **NumPy**:

> NumPy es el paquete fundamental para computación científica con Python.

[NumPy tiene una ingente cantidad de módulos y funciones](https://docs.scipy.org/doc/numpy/reference/index.html)

![Numpy usage](images/numpy/numpy_usage.png)

Fuente: [Python Developers Survey 2018](https://www.jetbrains.com/research/python-developers-survey-2018/)

# Guión

1. [Instalación](#Instalaci%C3%B3n)
2. [Creación de arrays](#Creaci%C3%B3n-de-arrays)
3. [Funciones predefinidas para crear arrays](#Funciones-predefinidas-para-crear-arrays)
4. [Acceso, borrado e inserción de elementos en arrays](#Acceso,-borrado-e-inserci%C3%B3n-de-elementos-en-arrays)
5. [*Slicing* de arrays](#Slicing-de-arrays)
6. [Indexado booleano, operaciones de conjunto y ordenación](#Indexado-booleano,-operaciones-de-conjunto-y-ordenaci%C3%B3n)
7. [Operaciones aritméticas y *broadcasting*](#Operaciones-aritm%C3%A9ticas-y-broadcasting)
8. [Álgebra lineal](#%C3%81lgebra-lineal)


# Instalación
---

![Instalación Numpy](images/numpy/numpy_installation.png)

# Creación de arrays
---

# `ndarray`

En el núcleo de NumPy está el **ndarray**, donde **nd** es por *n-dimensional*. Un ndarray es un **array multidimensional** de elementos **del mismo tipo**.

In [1]:
import numpy as np

x = np.array([1, 2, 3, 4, 5])
print('x =', x)

x = [1 2 3 4 5]


In [2]:
print('x has dimension: ', x.ndim)
print('x has size: ', x.size)
print('x has shape:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

x has dimension:  1
x has size:  5
x has shape: (5,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int64


# ndarrays con tipos heterogéneos. Me engañaron!

In [3]:
x = np.array([4, 'Einstein', 1e-7])

Se produce (*de forma implícita*) una [coerción de tipos](http://diccionario.raing.es/es/lema/coerci%C3%B3n-de-tipos) a **Unicode**:

In [4]:
print('x has dimension: ', x.ndim)
print('x has size: ', x.size)
print('x has shape:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

x has dimension:  1
x has size:  3
x has shape: (3,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: <U21


# Tipos de datos en NumPy

Como hemos visto, los arrays en NumPy tienen que ser de un [tipo fijo](https://www.numpy.org/devdocs/user/basics.types.html). Veamos los tipos numéricos más usados y sus características:

dtype | Descripción | Rango
- | - | -
np.int32 | Integer | -2147483648 to 2147483647
np.int64 | Integer (**por defecto**) | -9223372036854775808 to 9223372036854775807
np.uint32 | Unsigned integer | 0 to 4294967295
np.uint64 | Unsigned integer | 0 to 18446744073709551615
np.float32 | Float | -3.4028235e+38 to 3.4028235e+38
np.float64 | Float (**por defecto**) | -1.7976931348623157e+308 to 1.7976931348623157e+308

## Creando ndarrays con distintos tipos de datos

In [10]:
values = list(range(10))

array_int32 = np.array(values, dtype='int32')
array_int64 = np.array(values, dtype='int64')

array_float32 = np.array(values, dtype='float32')
array_float64 = np.array(values, dtype='float64')

In [19]:
array_int32

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [12]:
array_int64

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
array_float32

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [14]:
array_float64

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

# ¿Por qué ndarrays en vez de listas?

In [5]:
array_as_list = list(range(int(10e6)))
array_as_ndarray = np.array(array_as_list)

In [6]:
%timeit sum(array_as_list)

76.8 ms ± 1.02 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [7]:
%timeit array_as_ndarray.sum()

5.8 ms ± 114 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


# Mezclando enteros y flotantes

In [8]:
x = np.array([1, 2, 3])
y = np.array([1.0, 2.0, 3.0])
z = np.array([1, 2.5, 4])

In [9]:
print('The elements in x are of type:', x.dtype)
print('The elements in y are of type:', y.dtype)
print('The elements in z are of type:', z.dtype)

The elements in x are of type: int64
The elements in y are of type: float64
The elements in z are of type: float64


In [10]:
w = np.array([1.5, 2.2, 3.7, 4.0, 5.9], dtype = np.int64)
print(w, w.dtype)

[1 2 3 4 5] int64


# Convirtiendo arrays ya creados

In [11]:
x

array([1, 2, 3])

In [12]:
x.astype(float)

array([1., 2., 3.])

In [13]:
y

array([1., 2., 3.])

In [14]:
y.astype(int)

array([1, 2, 3])

# Matrices

$$
M=
  \begin{bmatrix}
    1 & 2 & 3 \\
    4 & 5 & 6 \\
    7 & 8 & 9 \\
    10 & 11 & 12
  \end{bmatrix}
$$

In [2]:
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
M

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [16]:
print('M has dimension: ', M.ndim)
print('M has size: ', M.size)
print('M has shape (rows, columns):', M.shape)
print('M is an object of type:', type(M))
print('The elements in M are of type:', M.dtype)

M has dimension:  2
M has size:  12
M has shape (rows, columns): (4, 3)
M is an object of type: <class 'numpy.ndarray'>
The elements in M are of type: int64


## 💡Ejercicio

Cree los siguientes arrays en NumPy:

`array1` =
$
\begin{align*}
  \begin{bmatrix}
    88 & 23 & 39 & 41
  \end{bmatrix}
\end{align*}
$
(como array unidimensional)

`array2` =
$
\begin{align*}
  \begin{bmatrix}
    76.4 & 21.7 & 38.4 \\
    41.2 & 52.8 & 68.9
  \end{bmatrix}
\end{align*}
$

`array3` =
$
\begin{align*}
  \begin{bmatrix}
    12 \\
    a \\
    9 \\
    b
  \end{bmatrix}
\end{align*}
$

, y obtenga los siguientes parámetros de cada uno de ellos:

- Dimensión.
- Tamaño.
- Forma.
- Tipo.
- Tipo de los elementos.

In [17]:
# Write your code here!

## ⭐️ Solución

In [18]:
# %load "solutions/numpy/first_arrays.py"

# Guardando y cargando arrays

In [19]:
M

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [20]:
# esto crea un fichero binario con el nombre my_matrix.npy
np.save('resources/numpy/my_matrix', M)

In [21]:
M_reloaded = np.load('resources/numpy/my_matrix.npy')

In [22]:
M_reloaded

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

El formato de fichero `.npy` es de tipo binario ([ver descripción](https://www.numpy.org/devdocs/reference/generated/numpy.lib.format.html))

# Guardando y cargando arrays con ficheros `.csv`

In [18]:
M

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [3]:
np.savetxt("resources/numpy/my_matrix.csv", M)

In [ ]:
# %load "resources/numpy/my_matrix.csv"
1.000000000000000000e+00 2.000000000000000000e+00 3.000000000000000000e+00
4.000000000000000000e+00 5.000000000000000000e+00 6.000000000000000000e+00
7.000000000000000000e+00 8.000000000000000000e+00 9.000000000000000000e+00
1.000000000000000000e+01 1.100000000000000000e+01 1.200000000000000000e+01


In [4]:
np.loadtxt("resources/numpy/my_matrix.csv")

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

## Cargando columnas en variables independientes

In [ ]:
# %load "resources/numpy/my_matrix.csv"
1.000000000000000000e+00 2.000000000000000000e+00 3.000000000000000000e+00
4.000000000000000000e+00 5.000000000000000000e+00 6.000000000000000000e+00
7.000000000000000000e+00 8.000000000000000000e+00 9.000000000000000000e+00
1.000000000000000000e+01 1.100000000000000000e+01 1.200000000000000000e+01


In [6]:
x, y, z = np.loadtxt("resources/numpy/my_matrix.csv", unpack=True)

In [11]:
x

array([ 1.,  4.,  7., 10.])

In [13]:
y

array([ 2.,  5.,  8., 11.])

In [14]:
z

array([ 3.,  6.,  9., 12.])

# Funciones predefinidas para crear arrays
---

# Ceros

In [69]:
import os

X = np.zeros((3, 4))

print(X, end=2 * os.linesep)

print('X has shape:', X.shape)
print('The elements in X are of type:', X.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

X has shape: (3, 4)
The elements in X are of type: float64


## Ceros (desde otro array)

Podemos necesitar tener un array de ceros con la misma forma que otro:

In [70]:
np.zeros_like(X)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Esto equivale a crear un array de ceros pero con la ventaja de no tener que especificar dimensiones:

In [71]:
np.zeros(X.shape)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Unos

In [24]:
X = np.ones((2, 3))    # también existe np.ones_like

print(X, end=2 * os.linesep)

print('X has shape:', X.shape)
print('The elements in X are of type:', X.dtype)

[[1. 1. 1.]
 [1. 1. 1.]]

X has shape: (2, 3)
The elements in X are of type: float64


Por defecto NumPy establece el tipo de los elementos a `float64` pero podemos cambiar este comportamiento pasando el parámetro `dtype` al llamar a la función generadora:

In [25]:
np.ones((3, 2), dtype=np.int64)

array([[1, 1],
       [1, 1],
       [1, 1]])

# Mismo valor

In [26]:
X = np.full((3, 3), 7)    # también existe np.full_like

print(X, end=2 * os.linesep)

print('X has shape:', X.shape)
print('The elements in X are of type:', X.dtype)

[[7 7 7]
 [7 7 7]
 [7 7 7]]

X has shape: (3, 3)
The elements in X are of type: int64


# Matriz identidad

In [27]:
X = np.eye(5)

print(X, end=2 * os.linesep)

print('X has shape:', X.shape)
print('The elements in X are of type:', X.dtype)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

X has shape: (5, 5)
The elements in X are of type: float64


# Matriz diagonal

In [28]:
X = np.diag([5, 4, 3, 2, 1])

print(X, end=2 * os.linesep)

print('X has shape:', X.shape)
print('The elements in X are of type:', X.dtype)

[[5 0 0 0 0]
 [0 4 0 0 0]
 [0 0 3 0 0]
 [0 0 0 2 0]
 [0 0 0 0 1]]

X has shape: (5, 5)
The elements in X are of type: int64


## 💡Ejercicio

Cree la siguiente matriz:

`diagonal` =
$
\begin{bmatrix} 
    0      & 0      & 0 & \dots & 0\\
    0      & 1      & 0 & \dots & 0\\
    0      & 0      & 2 & \dots & 0\\
    \vdots & \vdots & 0 & \ddots & 0\\
    0      & 0      & 0 & \dots & 49\\
    \end{bmatrix}
$

, y obtenga los siguientes parámetros de la misma:

- Dimensión.
- Tamaño.
- Forma.
- Tipo.
- Tipo de los elementos.

In [29]:
# Write your code here!

## ⭐️ Solución

In [30]:
# %load "solutions/numpy/diag_array.py"

# Arrays con valores enteros equiespaciados

In [31]:
X = np.arange(21)

print(X, end=2 * os.linesep)

print('X has dimension:', X.ndim)
print('X has size:', X.size)
print('The elements in X are of type:', X.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

X has dimension: 1
X has size: 21
The elements in X are of type: int64


In [32]:
X = np.arange(6, 60)

print(X, end=2 * os.linesep)

print('X has dimension:', X.ndim)
print('X has size:', X.size)
print('The elements in X are of type:', X.dtype)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29
 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

X has dimension: 1
X has size: 54
The elements in X are of type: int64


In [33]:
X = np.arange(6, 60, 3)

print(X, end=2 * os.linesep)

print('X has dimension:', X.ndim)
print('X has size:', X.size)
print('The elements in X are of type:', X.dtype)

[ 6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57]

X has dimension: 1
X has size: 18
The elements in X are of type: int64


# Arrays con valores flotantes equiespaciados

In [34]:
X = np.linspace(6, 60)

print(X, end=2 * os.linesep)

print('X has dimension:', X.ndim)
print('X has size:', X.size)
print('The elements in X are of type:', X.dtype)

[ 6.          7.10204082  8.20408163  9.30612245 10.40816327 11.51020408
 12.6122449  13.71428571 14.81632653 15.91836735 17.02040816 18.12244898
 19.2244898  20.32653061 21.42857143 22.53061224 23.63265306 24.73469388
 25.83673469 26.93877551 28.04081633 29.14285714 30.24489796 31.34693878
 32.44897959 33.55102041 34.65306122 35.75510204 36.85714286 37.95918367
 39.06122449 40.16326531 41.26530612 42.36734694 43.46938776 44.57142857
 45.67346939 46.7755102  47.87755102 48.97959184 50.08163265 51.18367347
 52.28571429 53.3877551  54.48979592 55.59183673 56.69387755 57.79591837
 58.89795918 60.        ]

X has dimension: 1
X has size: 50
The elements in X are of type: float64


In [35]:
X = np.linspace(6, 60, 75)

print(X, end=2 * os.linesep)

print('X has dimension:', X.ndim)
print('X has size:', X.size)
print('The elements in X are of type:', X.dtype)

[ 6.          6.72972973  7.45945946  8.18918919  8.91891892  9.64864865
 10.37837838 11.10810811 11.83783784 12.56756757 13.2972973  14.02702703
 14.75675676 15.48648649 16.21621622 16.94594595 17.67567568 18.40540541
 19.13513514 19.86486486 20.59459459 21.32432432 22.05405405 22.78378378
 23.51351351 24.24324324 24.97297297 25.7027027  26.43243243 27.16216216
 27.89189189 28.62162162 29.35135135 30.08108108 30.81081081 31.54054054
 32.27027027 33.         33.72972973 34.45945946 35.18918919 35.91891892
 36.64864865 37.37837838 38.10810811 38.83783784 39.56756757 40.2972973
 41.02702703 41.75675676 42.48648649 43.21621622 43.94594595 44.67567568
 45.40540541 46.13513514 46.86486486 47.59459459 48.32432432 49.05405405
 49.78378378 50.51351351 51.24324324 51.97297297 52.7027027  53.43243243
 54.16216216 54.89189189 55.62162162 56.35135135 57.08108108 57.81081081
 58.54054054 59.27027027 60.        ]

X has dimension: 1
X has size: 75
The elements in X are of type: float64


## Intervalo abierto $[a, b)$

In [36]:
X = np.linspace(6, 60, 75, endpoint=False)

print(X, end=2 * os.linesep)

print('X has dimension:', X.ndim)
print('X has size:', X.size)
print('The elements in X are of type:', X.dtype)

[ 6.    6.72  7.44  8.16  8.88  9.6  10.32 11.04 11.76 12.48 13.2  13.92
 14.64 15.36 16.08 16.8  17.52 18.24 18.96 19.68 20.4  21.12 21.84 22.56
 23.28 24.   24.72 25.44 26.16 26.88 27.6  28.32 29.04 29.76 30.48 31.2
 31.92 32.64 33.36 34.08 34.8  35.52 36.24 36.96 37.68 38.4  39.12 39.84
 40.56 41.28 42.   42.72 43.44 44.16 44.88 45.6  46.32 47.04 47.76 48.48
 49.2  49.92 50.64 51.36 52.08 52.8  53.52 54.24 54.96 55.68 56.4  57.12
 57.84 58.56 59.28]

X has dimension: 1
X has size: 75
The elements in X are of type: float64


# Creando matrices desde arrays unidimensionales

In [37]:
x = np.arange(20)
print(f'Original x{os.linesep}{x}')
print(f'Dimension: {x.ndim}; Shape: {x.shape}')

print()

x = np.reshape(x, (4, 5))
print(f'Reshaped x{os.linesep}{x}')
print(f'Dimension: {x.ndim}; Shape: {x.shape}')

Original x
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Dimension: 1; Shape: (20,)

Reshaped x
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Dimension: 2; Shape: (4, 5)


## Dimensiones por defecto

In [38]:
x = np.arange(3)
print(x)
print(f'Dimension: {x.ndim}; Shape: {x.shape}')

[0 1 2]
Dimension: 1; Shape: (3,)


In [39]:
# Redimensiona a 3 columnas (y busca las filas necesarias)
y = np.reshape(x, (-1, 3))
print(y)
print(f'Dimension: {y.ndim}; Shape: {y.shape}')


[[0 1 2]]
Dimension: 2; Shape: (1, 3)


In [40]:
# Redimensiona a 3 filas (y busca las columnas necesarias)
y = np.reshape(x, (3, -1))
print(y)
print(f'Dimension: {y.ndim}; Shape: {y.shape}')

[[0]
 [1]
 [2]]
Dimension: 2; Shape: (3, 1)


## Agrupando en una única línea

In [41]:
# very common one-liner
np.arange(20).reshape(4, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# Generando valores aleatorios enteros en $[a, b)$

In [42]:
X = np.random.randint(3, 30, size=(4, 5))

print(X, end=2 * os.linesep)

print('X has dimension:', X.ndim)
print('X has shape:', X.shape)
print('The elements in X are of type:', X.dtype)

[[ 5 27 11  9 11]
 [ 4 20 18  3 14]
 [ 8  6 20  3 14]
 [ 4 16 22 10  5]]

X has dimension: 2
X has shape: (4, 5)
The elements in X are of type: int64


# Generando valores aleatorios flotantes en $[0, 1)$

In [43]:
X = np.random.random((4, 5))

print(X, end=2 * os.linesep)

print('X has dimension:', X.ndim)
print('X has shape:', X.shape)
print('The elements in X are of type:', X.dtype)

[[0.37461078 0.27596013 0.52112373 0.59147087 0.95804405]
 [0.35126053 0.74210132 0.79353468 0.48526393 0.41969373]
 [0.55328573 0.69101149 0.86199791 0.63271154 0.12477632]
 [0.75532374 0.62336912 0.27101357 0.56885999 0.45473491]]

X has dimension: 2
X has shape: (4, 5)
The elements in X are of type: float64


# Generando valores aleatorios flotantes  en $[a, b)$

In [44]:
np.random.uniform(1, 1000, size=(50, 50))

array([[ 64.07027202, 323.02280764, 903.96355369, ..., 188.64027361,
        634.93899564, 360.72635333],
       [920.47039617, 340.13620213, 325.11855851, ..., 253.61329874,
        784.8625277 , 139.09867601],
       [800.08894247,  96.58668702, 861.46886324, ..., 440.25164151,
         94.3666558 , 887.97100356],
       ...,
       [689.80390656, 876.67305291, 730.80892506, ..., 709.78619121,
        153.78231925,  97.27964276],
       [206.55811292, 176.64450988,  48.22043149, ..., 421.57568597,
         33.38333228,  52.91739853],
       [259.23590445, 521.42890164, 760.95056995, ..., 727.95790083,
        116.2484708 , 809.57715037]])

# Generando valores aleatorios flotantes (distribución normal)

Supongamos: $ \mu = 0, \sigma = 5 $

In [45]:
np.random.normal(0, 5, size=(1000, 1000))

array([[ -1.63067828, -11.75412404,   3.04681872, ...,  -4.71594397,
         -1.29550666,  -9.67838622],
       [  8.44524891,  -3.52416624,  -0.16064105, ...,  -1.56996633,
          3.12102635,  -2.32125533],
       [  1.00888679,  -2.85798337,   2.51060864, ...,   1.17203781,
          2.98597652,  -9.59459707],
       ...,
       [ 13.39638749,   4.92401131,   9.7583337 , ...,  -6.46660979,
          1.58059938,   3.46359955],
       [  6.62104493,   3.46516444,   6.38317463, ...,   1.03685305,
          1.22405814,  -8.09148333],
       [  2.27689812,   6.54786003,  -0.32908949, ...,  -2.74017764,
          4.00166125,  -2.07166082]])

In [46]:
print('X has dimensions:', X.ndim)
print('X has shape: ', X.shape)
print('X has size: ', X.size)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)
print('The elements in X have a mean of:', X.mean())
print('The elements in X have a std deviation of:', X.std())
print('The maximum value in X is:', X.max())
print('The minimum value in X is:', X.min())
print('X has', (X < 0).sum(), 'negative numbers')
print('X has', (X > 0).sum(), 'positive numbers')

X has dimensions: 2
X has shape:  (4, 5)
X has size:  20
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64
The elements in X have a mean of: 0.5525074028827668
The elements in X have a std deviation of: 0.20873027467622537
The maximum value in X is: 0.9580440483847021
The minimum value in X is: 0.12477631640470777
X has 0 negative numbers
X has 20 positive numbers


## 💡Ejercicio

Cree:

- Una matriz de 20 filas y 5 columnas con valores flotantes equiespaciados en el intervalo cerrado $[1, 10]$
- Un array unidimensional con 128 valores aleatorios de una distribución normal $\mu=1, \sigma=2$

In [47]:
# Write your code here!

## ⭐️ Solución

In [48]:
# %load "solutions/numpy/rand_arrays.py"

# Muestra aleatoria de un conjunto de valores

Supongamos que queremos generar una muestra aleatoria de un millón de lanzamientos de una moneda.

In [52]:
coins = np.random.choice(['head', 'tail'], size=1_000_000)
coins

array(['tail', 'head', 'head', ..., 'tail', 'head', 'head'], dtype='<U4')

In [53]:
heads = np.count_nonzero(coins == 'head')
tails = np.count_nonzero(coins == 'tail')

heads_pct = heads / coins.size * 100
tails_pct = tails / coins.size * 100

print(f'{heads_pct:.4}% heads')
print(f'{tails_pct:.4}% tails')

49.98% heads
50.02% tails


## Probabilidades no uniformes

Supongamos que vamos a una casa de apuestas. Tiramos un millón veces pero hay algo que no nos cuadra. El dado está trucado! 😱

In [55]:
dices = np.random.choice(range(1, 7), size=1_000_000, p=[.5, .1, .1, .1, .1, .1])
dices

array([3, 4, 2, ..., 1, 6, 1])

In [62]:
values, counts = np.unique(dices, return_counts=True)
for value, count in zip(unique, counts):
    value_pct = count / dices.size * 100
    print(f'{value}: {value_pct:.4}%')

1: 49.94%
2: 9.971%
3: 9.992%
4: 10.03%
5: 10.03%
6: 10.03%


## Selección sin reemplazo

Axiomas:

- [Juego de Tronos](https://es.wikipedia.org/wiki/Game_of_Thrones) es una gran serie.
- En la serie se producen muchas muertes.
- Si una persona muere, no puede volver a morir (🤔)

Vamos a partir de 15 personajes de Juego de Tronos y dejar que NumPy elija quién vive 👍🏻 y quién muere 👎🏻. Sólo pueden quedar 3!

In [68]:
participants = ['Arya Stark', 'Daenerys Targaryen', 'Jon Snow', 'Melisandre', 'Bran Stark', 'Cersei Lannister',
                'Gendry', 'Gregor Clegane', 'Jorah Mormont', 'Sansa Stark', 'Theon Greyjoy', 'Tyrion Lannister',
               'Bronn', 'Brienne de Tarth', 'Tormund Giantsbane']

dead = np.random.choice(participants, size=len(participants) - 3, replace=False)
np.setdiff1d(participants, dead)   # alive

array(['Arya Stark', 'Jorah Mormont', 'Tormund Giantsbane'], dtype='<U18')

# Acceso, borrado e inserción de elementos en arrays
---

![NumPy Arrays](images/numpy/numpy_arrays.png)

Photo by [Harriet Dashnow, Stéfan van der Walt, Juan Núñez-Iglesias](https://www.oreilly.com/library/view/elegant-scipy/9781491922927/ch01.html) on [O'Reilly](https://www.oreilly.com/library/view/elegant-scipy/9781491922927/)

# Acceso a elementos de arrays unidimensionales

In [49]:
x = np.arange(10, 16)
x

array([10, 11, 12, 13, 14, 15])

In [50]:
for i in range(x.size):
    print(f'[{i}] {x[i]}')

[0] 10
[1] 11
[2] 12
[3] 13
[4] 14
[5] 15


In [51]:
for i in range(1, x.size + 1):
    print(f'[{-i}] {x[-i]}')

[-1] 15
[-2] 14
[-3] 13
[-4] 12
[-5] 11
[-6] 10


# Modificación de valores de arrays unidimensionales

In [52]:
x

array([10, 11, 12, 13, 14, 15])

In [53]:
x[0] *= 10
x[-1] /= 10

In [54]:
x

array([100,  11,  12,  13,  14,   1])

# Borrado e inserción en arrays unidimensionales

In [55]:
x

array([100,  11,  12,  13,  14,   1])

In [56]:
# borramos el primer y el cuarto elemento del array
x = np.delete(x, (0, 3))
x

array([11, 12, 14,  1])

In [57]:
x = np.append(x, 99)
x

array([11, 12, 14,  1, 99])

In [58]:
# insertamos [3, 7] delante del tercer elemento
x = np.insert(x, 2, [3, 7])
x

array([11, 12,  3,  7, 14,  1, 99])

# Acceso a alementos de arrays multidimensionales

In [59]:
X = np.random.randint(1, 12, size=(3, 4))
X

array([[ 8, 11,  1, 10],
       [ 9,  3,  5, 10],
       [ 1,  4,  8,  8]])

In [60]:
X[0, 0]

8

In [61]:
X[2, 3]

8

In [62]:
X[-1, -1]

8

In [63]:
X[[0, 2], [1, 3]]   # equivale a: X[0, 1], X[2, 3]

array([11,  8])

# Acceso a filas o columnas completas

In [64]:
X

array([[ 8, 11,  1, 10],
       [ 9,  3,  5, 10],
       [ 1,  4,  8,  8]])

In [65]:
X[2]   # tercera fila

array([1, 4, 8, 8])

In [66]:
X[:,1] # segunda columna

array([11,  3,  4])

# Modificación de valores de arrays multidimensionales

In [67]:
X

array([[ 8, 11,  1, 10],
       [ 9,  3,  5, 10],
       [ 1,  4,  8,  8]])

In [68]:
X[1, 1] *= 100
X

array([[  8,  11,   1,  10],
       [  9, 300,   5,  10],
       [  1,   4,   8,   8]])

In [69]:
X[0] = [1, 2, 3, 4]
X

array([[  1,   2,   3,   4],
       [  9, 300,   5,  10],
       [  1,   4,   8,   8]])

In [70]:
X[:,2] = 5
X

array([[  1,   2,   5,   4],
       [  9, 300,   5,  10],
       [  1,   4,   5,   8]])

# Borrado en arrays multidimensionales

In [71]:
X

array([[  1,   2,   5,   4],
       [  9, 300,   5,  10],
       [  1,   4,   5,   8]])

In [72]:
# borramos la primera fila de la matriz
X = np.delete(X, 0, axis=0)
X

array([[  9, 300,   5,  10],
       [  1,   4,   5,   8]])

In [73]:
# borramos la segunda y cuarta columnas de la matriz
X = np.delete(X, (1, 3), axis=1)
X

array([[9, 5],
       [1, 5]])

# Añadiendo elementos a arrays multidimensionales

In [74]:
X

array([[9, 5],
       [1, 5]])

In [75]:
X = np.append(X, [[3, 7]], axis=0)
X

array([[9, 5],
       [1, 5],
       [3, 7]])

In [76]:
X = np.append(X, [[3], [4], [5]], axis=1)
X

array([[9, 5, 3],
       [1, 5, 4],
       [3, 7, 5]])

# Insertando elementos en arrays multidimensionales

In [77]:
X

array([[9, 5, 3],
       [1, 5, 4],
       [3, 7, 5]])

In [78]:
# insertamos [2, 2, 2] antes de la segunda fila
X = np.insert(X, 1, [2, 2, 2], axis=0)
X

array([[9, 5, 3],
       [2, 2, 2],
       [1, 5, 4],
       [3, 7, 5]])

In [79]:
# insertamos [9, 8, 7, 6] antes de la tercera columna
X = np.insert(X, 2, [9, 8, 7, 6], axis=1)
X

array([[9, 5, 9, 3],
       [2, 2, 8, 2],
       [1, 5, 7, 4],
       [3, 7, 6, 5]])

## 💡Ejercicio

Utilizando las operaciones de modificación, borrado e inserción, convierta la siguiente matriz:

$
\begin{align*}
  \begin{bmatrix}
    17 & 12 & 31 \\
    49 & 11 & 51 \\
    21 & 31 & 62 \\
    63 & 75 & 22
  \end{bmatrix}
\end{align*}
$

en ésta:

$
\begin{align*}
  \begin{bmatrix}
    17 & 12 & 31 & 63\\
    49 & 11 & 51 & 75\\
    21 & 31 & 62 & 22\\
  \end{bmatrix}
\end{align*}
$

y luego en ésta:

$
\begin{align*}
  \begin{bmatrix}
    17 & 12 & 31 & 63\\
    49 & 49 & 49 & 63\\
    21 & 31 & 62 & 63\\
  \end{bmatrix}
\end{align*}
$


In [80]:
# Write your code here!

## ⭐️ Solución

In [81]:
# %load "solutions/numpy/transform.py"

# Apilando matrices (vertical)

In [82]:
A = np.random.randint(1, 100, size=(3, 2))
B = np.random.randint(1, 100, size=(1, 2))

In [83]:
A

array([[34, 48],
       [96,  8],
       [13, 72]])

In [84]:
B

array([[34, 60]])

In [85]:
np.vstack((A, B))

array([[34, 48],
       [96,  8],
       [13, 72],
       [34, 60]])

# Apilando matrices (horizontal)

In [86]:
A = np.random.randint(1, 100, size=(3, 2))
B = np.random.randint(1, 100, size=(3, 1))

In [87]:
A

array([[59,  9],
       [ 8, 86],
       [92, 88]])

In [88]:
B

array([[11],
       [99],
       [30]])

In [89]:
np.hstack((A, B))

array([[59,  9, 11],
       [ 8, 86, 99],
       [92, 88, 30]])

# Repitiendo elementos con `tile`

In [7]:
X = np.random.randint(1, 100, size=(3, 2))
X

array([[74, 94],
       [39, 37],
       [ 2, 45]])

In [8]:
np.tile(X, 3)

array([[74, 94, 74, 94, 74, 94],
       [39, 37, 39, 37, 39, 37],
       [ 2, 45,  2, 45,  2, 45]])

In [14]:
np.tile(X, (2, 3))

array([[74, 94, 74, 94, 74, 94],
       [39, 37, 39, 37, 39, 37],
       [ 2, 45,  2, 45,  2, 45],
       [74, 94, 74, 94, 74, 94],
       [39, 37, 39, 37, 39, 37],
       [ 2, 45,  2, 45,  2, 45]])

# Repitiendo elementos con `repeat`

In [21]:
X

array([[74, 94],
       [39, 37],
       [ 2, 45]])

In [20]:
np.repeat(X, 2)

array([74, 74, 94, 94, 39, 39, 37, 37,  2,  2, 45, 45])

In [26]:
np.repeat(X, 2, axis=0)

array([[74, 94],
       [74, 94],
       [39, 37],
       [39, 37],
       [ 2, 45],
       [ 2, 45]])

In [28]:
np.repeat(X, 3, axis=1)

array([[74, 74, 74, 94, 94, 94],
       [39, 39, 39, 37, 37, 37],
       [ 2,  2,  2, 45, 45, 45]])

# *Slicing* de arrays
---

In [90]:
X = np.random.randint(1, 100, size=(5, 4))
X

array([[98, 90, 22, 17],
       [91, 96, 46, 54],
       [71, 64, 48, 19],
       [46, 11,  5, 35],
       [44, 89, 58, 38]])

In [91]:
np.vstack((X[0], X[-1]))

array([[98, 90, 22, 17],
       [44, 89, 58, 38]])

In [92]:
first_column = X[:, 0].reshape(-1, 1)
last_column = X[:, -1].reshape(-1, 1)
np.hstack((first_column, last_column))

array([[98, 17],
       [91, 54],
       [71, 19],
       [46, 35],
       [44, 38]])

In [93]:
X[:, :2]

array([[98, 90],
       [91, 96],
       [71, 64],
       [46, 11],
       [44, 89]])

In [94]:
X[::-1]   # equivalente a X[::-1, ] y a X[::-1, :]

array([[44, 89, 58, 38],
       [46, 11,  5, 35],
       [71, 64, 48, 19],
       [91, 96, 46, 54],
       [98, 90, 22, 17]])

In [95]:
X[:, ::-1]

array([[17, 22, 90, 98],
       [54, 46, 96, 91],
       [19, 48, 64, 71],
       [35,  5, 11, 46],
       [38, 58, 89, 44]])

# Subarrays (vistas de un array)

In [96]:
X

array([[98, 90, 22, 17],
       [91, 96, 46, 54],
       [71, 64, 48, 19],
       [46, 11,  5, 35],
       [44, 89, 58, 38]])

In [97]:
X[0:2, 0:2]

array([[98, 90],
       [91, 96]])

In [98]:
X[3:, 1:]

array([[11,  5, 35],
       [89, 58, 38]])

In [99]:
X[:, 2:]

array([[22, 17],
       [46, 54],
       [48, 19],
       [ 5, 35],
       [58, 38]])

# Modificación de vistas (subarrays)

In [100]:
X

array([[98, 90, 22, 17],
       [91, 96, 46, 54],
       [71, 64, 48, 19],
       [46, 11,  5, 35],
       [44, 89, 58, 38]])

In [101]:
my_array_view = X[2:, 2:]
my_array_view[0, 0] = 9999
my_array_view

array([[9999,   19],
       [   5,   35],
       [  58,   38]])

In [102]:
X

array([[  98,   90,   22,   17],
       [  91,   96,   46,   54],
       [  71,   64, 9999,   19],
       [  46,   11,    5,   35],
       [  44,   89,   58,   38]])

# Creando copias "desvinculadas" de arrays

In [103]:
X

array([[  98,   90,   22,   17],
       [  91,   96,   46,   54],
       [  71,   64, 9999,   19],
       [  46,   11,    5,   35],
       [  44,   89,   58,   38]])

In [104]:
my_array_view = np.copy(X[:, :2])
my_array_view[0, 0] = 1111
my_array_view

array([[1111,   90],
       [  91,   96],
       [  71,   64],
       [  46,   11],
       [  44,   89]])

In [105]:
X

array([[  98,   90,   22,   17],
       [  91,   96,   46,   54],
       [  71,   64, 9999,   19],
       [  46,   11,    5,   35],
       [  44,   89,   58,   38]])

# Extraer elementos con referencia de diagonal

In [106]:
X = np.random.randint(10, 100, size=(4, 4))
X

array([[58, 73, 94, 99],
       [32, 79, 81, 37],
       [99, 93, 72, 96],
       [42, 95, 32, 30]])

In [107]:
np.diag(X)

array([58, 79, 72, 30])

In [108]:
for k in range(1, X.shape[0]):
    print(np.diag(X, k=k))

[73 81 96]
[94 37]
[99]


In [109]:
for k in range(1, X.shape[0]):
    print(np.diag(X, k=-k))

[32 93 32]
[99 95]
[42]


## Modificando elementos de la diagonal principal

NumPy también provee un método que retorna los *índices de los elementos de la diagonal principal*, con lo que podemos modificar sus valores directamente:

In [110]:
X

array([[58, 73, 94, 99],
       [32, 79, 81, 37],
       [99, 93, 72, 96],
       [42, 95, 32, 30]])

In [111]:
di = np.diag_indices(X.shape[0])
di

(array([0, 1, 2, 3]), array([0, 1, 2, 3]))

In [112]:
X[di] = 1
X

array([[ 1, 73, 94, 99],
       [32,  1, 81, 37],
       [99, 93,  1, 96],
       [42, 95, 32,  1]])

# Extraer valores únicos de un array

In [113]:
X = np.random.randint(1, 10, size=(5, 5))
X

array([[9, 3, 7, 4, 4],
       [2, 7, 2, 5, 2],
       [7, 4, 2, 5, 6],
       [5, 1, 8, 2, 9],
       [7, 6, 7, 6, 1]])

In [114]:
np.unique(X)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Indexado booleano, operaciones de conjunto y ordenación
---

# Indexado booleano

In [115]:
X

array([[9, 3, 7, 4, 4],
       [2, 7, 2, 5, 2],
       [7, 4, 2, 5, 6],
       [5, 1, 8, 2, 9],
       [7, 6, 7, 6, 1]])

In [116]:
X > 5

array([[ True, False,  True, False, False],
       [False,  True, False, False, False],
       [ True, False, False, False,  True],
       [False, False,  True, False,  True],
       [ True,  True,  True,  True, False]])

In [117]:
X[X > 5]   # Nótese que se devuelve un array unidimensional

array([9, 7, 7, 7, 6, 8, 9, 7, 6, 7, 6])

## Condiciones compuestas

In [118]:
X

array([[9, 3, 7, 4, 4],
       [2, 7, 2, 5, 2],
       [7, 4, 2, 5, 6],
       [5, 1, 8, 2, 9],
       [7, 6, 7, 6, 1]])

In [119]:
X[(X == 1) | (X > 8)]

array([9, 1, 9, 1])

In [120]:
# los paréntesis son obligatorios para que funcione
X[(X > 3) & (X < 6)]

array([4, 4, 5, 4, 5, 5])

## Modificando valores

Supongamos que queremos que todos los valores menores de 5 sean incrementados un 25%:

In [121]:
X

array([[9, 3, 7, 4, 4],
       [2, 7, 2, 5, 2],
       [7, 4, 2, 5, 6],
       [5, 1, 8, 2, 9],
       [7, 6, 7, 6, 1]])

In [122]:
X[X < 5] *= 1.25

TypeError: Cannot cast ufunc multiply output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

Convertimos la matriz a valores flotantes para poder hacer la operación:

In [123]:
X = X.astype(float)
X

array([[9., 3., 7., 4., 4.],
       [2., 7., 2., 5., 2.],
       [7., 4., 2., 5., 6.],
       [5., 1., 8., 2., 9.],
       [7., 6., 7., 6., 1.]])

In [124]:
X[X < 5] *= 1.25
X

array([[9.  , 3.75, 7.  , 5.  , 5.  ],
       [2.5 , 7.  , 2.5 , 5.  , 2.5 ],
       [7.  , 5.  , 2.5 , 5.  , 6.  ],
       [5.  , 1.25, 8.  , 2.5 , 9.  ],
       [7.  , 6.  , 7.  , 6.  , 1.25]])

## 💡Ejercicio

Extraiga todos los números impares del array $\big[0, 1, 2, 3, 4, 5, 6, 7, 8, 9 \big]$

In [125]:
# Write your code here!

## ⭐️ Solución

In [126]:
# %load "solutions/numpy/extract_odds.py"

# Comprobando si dos arrays son iguales

In [127]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[1, 2], [3, 4]])
C = np.array([[1, 3], [2, 4]])

In [128]:
A == B

array([[ True,  True],
       [ True,  True]])

In [129]:
np.array_equal(A, B)

True

In [130]:
A == C

array([[ True, False],
       [False,  True]])

In [131]:
np.array_equal(A, C)

False

# Obteniendo índices en vez de valores

Supongamos que queremos obtener aquellos **índices** de la matriz $\mathcal{M}$ que satisfacen una condición concreta:

In [132]:
M = np.random.randint(1, 100, size=(4, 4))
M

array([[83, 96, 46, 79],
       [58, 32, 63, 84],
       [ 7, 27, 31, 63],
       [35, 58, 91, 25]])

In [133]:
M > 50

array([[ True,  True, False,  True],
       [ True, False,  True,  True],
       [False, False, False,  True],
       [False,  True,  True, False]])

In [134]:
M[M > 50]

array([83, 96, 79, 58, 63, 84, 63, 58, 91])

## ¿Y los índices? $\Rightarrow$ Usar `where`

In [135]:
idx = np.where(M > 50)
idx

(array([0, 0, 0, 1, 1, 1, 2, 3, 3]), array([0, 1, 3, 0, 2, 3, 3, 1, 2]))

In [136]:
M[idx]

array([83, 96, 79, 58, 63, 84, 63, 58, 91])

## 💡Ejercicio

Partiendo de una matriz de 10 filas y 10 columnas con valores aleatorios enteros en el intervalo $[0, 100]$, realice las operaciones necesarias para obtener una matriz de las mismas dimensiones donde:

- Todos los elementos de la diagonal sean 50.
- Los elementos mayores que 50 tengan valor 100.
- Los elementos menores que 50 tengan valor 0.

In [137]:
# Write your code here!

## ⭐️ Solución

In [225]:
# %load "solutions/numpy/diag_transform.py"

# Operaciones de conjunto

In [139]:
x, y = np.random.randint(1, 20, 10), np.random.randint(1, 20, 10)
print('x =', x)
print('y =', y)

x = [ 3 16 19  4 18  8  6  5 18 16]
y = [16 19 14  8 19 16  8  3  2 15]


In [140]:
np.intersect1d(x, y)

array([ 3,  8, 16, 19])

In [141]:
np.setdiff1d(x, y)

array([ 4,  5,  6, 18])

In [142]:
np.union1d(x, y)

array([ 2,  3,  4,  5,  6,  8, 14, 15, 16, 18, 19])

# Ordenación en arrays unidimensionales

In [143]:
x

array([ 3, 16, 19,  4, 18,  8,  6,  5, 18, 16])

In [144]:
np.sort(x)

array([ 3,  4,  5,  6,  8, 16, 16, 18, 18, 19])

In [145]:
y

array([16, 19, 14,  8, 19, 16,  8,  3,  2, 15])

In [146]:
np.sort(y)

array([ 2,  3,  8,  8, 14, 15, 16, 16, 19, 19])

# Cambiando los métodos de ordenación

In [228]:
big_array = np.random.uniform(1, 10000, 10_000_000)

### Quicksort

In [148]:
%timeit np.sort(big_array, kind='quicksort')  # método por defecto

930 ms ± 3.98 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


### Mergesort

In [149]:
%timeit np.sort(big_array, kind='mergesort')

1.14 s ± 7.45 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


### Heapsort

In [150]:
%timeit np.sort(big_array, kind='heapsort')

2.91 s ± 11.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


# Ordenación en arrays multidimensionales

In [151]:
X = np.random.randint(1, 100, size=(4, 4))
X

array([[60, 58, 31, 45],
       [23, 35, 36, 25],
       [99, 42,  4, 32],
       [ 2, 43, 50, 96]])

In [152]:
# ordenamos por columnas (dirección eje de filas)
np.sort(X, axis=0)

array([[ 2, 35,  4, 25],
       [23, 42, 31, 32],
       [60, 43, 36, 45],
       [99, 58, 50, 96]])

In [153]:
# ordenamos por filas (dirección eje de columnas)
np.sort(X, axis=1)

array([[31, 45, 58, 60],
       [23, 25, 35, 36],
       [ 4, 32, 42, 99],
       [ 2, 43, 50, 96]])

# Contando valores

Supongamos que tenemos una distribución aleatoria uniforme de valores enteros entre 1 y 10:

In [120]:
X = np.random.randint(1, 11, size=1000)

Queremos obtener los valores **únicos** que hay en el array:

In [121]:
np.unique(X)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Pero ahora queremos obtener también cuantas apariciones hay de cada valor:

In [123]:
np.unique(X, return_counts=True)

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([ 85, 102, 109, 106,  96,  99,  94, 103, 100, 106]))

## Contando a partir de filtrado

NumPy nos ofrece una función para contar los valores distintos de cero dentro de un array:

In [126]:
np.count_nonzero(X)

1000

Pero podemos utilizarlo para propósitos más ambiciosos. Supongamos que queremos saber cuántos valores de nuestro array son mayores que 5:

In [127]:
np.count_nonzero(X > 5)

502

# Operaciones aritméticas y broadcasting
---

# Operaciones aritméticas entre arrays

In [138]:
X, Y = np.random.randint(1, 100, size=(3, 3)), np.random.randint(1, 100, size=(3, 3))
print(f'X = {os.linesep}{X}')
print()
print(f'Y = {os.linesep}{Y}')

X = 
[[86 77 47]
 [45 38 19]
 [96 69 20]]

Y = 
[[24 98 83]
 [29 48 89]
 [76  7 53]]


In [139]:
X + Y

array([[110, 175, 130],
       [ 74,  86, 108],
       [172,  76,  73]])

In [140]:
X - Y

array([[ 62, -21, -36],
       [ 16, -10, -70],
       [ 20,  62, -33]])

In [141]:
print(f'X = {os.linesep}{X}')
print()
print(f'Y = {os.linesep}{Y}')

X = 
[[86 77 47]
 [45 38 19]
 [96 69 20]]

Y = 
[[24 98 83]
 [29 48 89]
 [76  7 53]]


In [142]:
X * Y

array([[2064, 7546, 3901],
       [1305, 1824, 1691],
       [7296,  483, 1060]])

In [143]:
X / Y

array([[3.58333333, 0.78571429, 0.56626506],
       [1.55172414, 0.79166667, 0.21348315],
       [1.26315789, 9.85714286, 0.37735849]])

# Operaciones aritméticas entre arrays de distintas dimensiones

## Suma con array "fila"

In [144]:
X = np.random.randint(1, 10, size=(2, 3))
X

array([[6, 2, 9],
       [4, 4, 3]])

In [145]:
y = np.random.randint(1, 10, size=(1, 3))
y

array([[2, 4, 5]])

In [146]:
X + y

array([[ 8,  6, 14],
       [ 6,  8,  8]])

## Suma con array "columna"

In [147]:
X

array([[6, 2, 9],
       [4, 4, 3]])

In [148]:
y = np.random.randint(1, 10, size=(2, 1))
y

array([[5],
       [9]])

In [149]:
X + y

array([[11,  7, 14],
       [13, 13, 12]])

# Operaciones entre arrays y escalares

In [179]:
X

array([[70,  9, 86],
       [24, 47, 38],
       [14, 79, 49]])

In [180]:
X + 10

array([[80, 19, 96],
       [34, 57, 48],
       [24, 89, 59]])

In [181]:
X - 10

array([[60, -1, 76],
       [14, 37, 28],
       [ 4, 69, 39]])

In [182]:
X

array([[70,  9, 86],
       [24, 47, 38],
       [14, 79, 49]])

In [183]:
X * 10

array([[700,  90, 860],
       [240, 470, 380],
       [140, 790, 490]])

In [184]:
X / 10

array([[7. , 0.9, 8.6],
       [2.4, 4.7, 3.8],
       [1.4, 7.9, 4.9]])

In [137]:
X ** 3

array([[328509, 205379,  39304],
       [  4096, 157464, 238328],
       [658503, 117649, 681472]])

# Funciones universales sobre arrays

Las funciones universales (**ufunc**) son funciones que operan sobre arrays **elemento a elemento**. Existen [muchas funciones universales definidas en Numpy](https://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs).

In [170]:
X = np.random.randint(1, 100, size=(3, 3))
X

array([[34, 94, 70],
       [62, 57, 89],
       [89, 30, 84]])

In [171]:
# Ejemplo de función universal de operación matemática
np.sqrt(X)

array([[5.83095189, 9.69535971, 8.36660027],
       [7.87400787, 7.54983444, 9.43398113],
       [9.43398113, 5.47722558, 9.16515139]])

In [172]:
# Ejemplo de función universal trigonométrica
np.sin(X)

array([[ 0.52908269, -0.24525199,  0.77389068],
       [-0.7391807 ,  0.43616476,  0.86006941],
       [ 0.86006941, -0.98803162,  0.73319032]])

# Funciones de reducción sobre arrays

Es posible utilizar cualquier función universal para realizar reducción sobre un array.

In [175]:
X

array([[34, 94, 70],
       [62, 57, 89],
       [89, 30, 84]])

In [176]:
np.add.reduce(X, axis=0)

array([185, 181, 243])

In [177]:
np.add.reduce(X, axis=1)

array([198, 208, 203])

In [173]:
X

array([[34, 94, 70],
       [62, 57, 89],
       [89, 30, 84]])

# Suma y producto sobre un array

In [178]:
X

array([[34, 94, 70],
       [62, 57, 89],
       [89, 30, 84]])

In [179]:
np.sum(X), np.sum(X, axis=1)

(609, array([198, 208, 203]))

In [180]:
np.prod(X), np.prod(X, axis=0)

(15781631917161600, array([187612, 160740, 523320]))

## 💡Ejercicio

Compruebe que, para $\theta=30$ y $k=20$ se cumple la siguiente igualdad del *producto infinito de Euler*:

$$
\cos\left({\frac{\theta}{2}}\right) \cdot
\cos\left({\frac{\theta}{4}}\right) \cdot
\cos\left({\frac{\theta}{8}}\right) \cdots
=
\prod_{i=1}^k \cos\left(\frac{\theta}{2^i}\right)
\approx
\frac{\sin(\theta)}{\theta}
$$


In [ ]:
# Write your code here!

## ⭐️ Solución

In [182]:
# %load "solutions/numpy/euler_product.py"

# Funciones estadísticas sobre un array

In [155]:
X

array([[ 5, 29, 34],
       [53,  3, 61],
       [33, 71, 34]])

In [156]:
np.mean(X), np.mean(X, axis=0)

(35.888888888888886, array([30.33333333, 34.33333333, 43.        ]))

In [157]:
np.std(X), np.std(X, axis=1)

(21.743169780387714, array([12.6578917 , 25.66450207, 17.68238295]))

In [158]:
np.median(X), np.median(X, axis=0)

(34.0, array([33., 29., 34.]))

# Encontrando máximos y mínimos

In [159]:
X

array([[ 5, 29, 34],
       [53,  3, 61],
       [33, 71, 34]])

In [160]:
np.min(X), np.min(X, axis=0)

(3, array([ 5,  3, 34]))

In [161]:
np.max(X), np.max(X, axis=1)

(71, array([34, 61, 71]))

## Índices de máximos y mínimos

In [98]:
X

array([[29, 88, 20],
       [99, 16, 15],
       [96, 57, 84]])

In [101]:
np.argmin(X), np.argmin(X, axis=0)

(5, array([0, 1, 1]))

In [103]:
np.argmax(X), np.argmax(X, axis=1)

(3, array([1, 0, 0]))

# Vectorizando funciones

Supongamos que queremos calcular el valor máximo entre dos matrices elemento a elemento. Podemos hacer una función que reciba *arrays* como parámetros:

In [154]:
def maxx(x, y):
    return x if x > y else y

In [155]:
X = np.random.randint(1, 100, size=(3, 3))
Y = np.random.randint(1, 100, size=(3, 3))

In [156]:
pair_max = np.vectorize(maxx)

In [157]:
print(f'X = {os.linesep}{X}')
print()
print(f'Y = {os.linesep}{Y}')

X = 
[[34 17 13]
 [61  6 27]
 [93 80 10]]

Y = 
[[42 31 55]
 [89 66 29]
 [54 68 54]]


In [158]:
pair_max(X, Y)

array([[42, 31, 55],
       [89, 66, 29],
       [93, 80, 54]])

## 💡Ejercicio

1. Cree dos matrices cuadradas de 20x20 con valores aleatorios flotantes uniformes en el intervalo $[0, 1000)$
2. Vectorice una función que devuelva la media (elemento a elemento) entre las dos matrices.
3. Realice la misma operación que en 2) pero usando suma de matrices y división por escalar.
4. Compute los tiempos de ejecución de 2) y 3)

In [87]:
# Write your code here!

## ⭐️ Solución

In [88]:
# %load "solutions/numpy/vectorize.py"

# Álgebra lineal
---

# Producto de matrices

In [191]:
A = np.random.randint(1, 10, size=(3, 3))
B = np.random.randint(1, 10, size=(3, 3))

print(f'A: {os.linesep}{A}')
print()
print(f'B: {os.linesep}{B}')

A: 
[[7 5 2]
 [4 1 3]
 [9 6 4]]

B: 
[[7 3 3]
 [8 9 8]
 [2 9 1]]


In [192]:
np.dot(A, B)

array([[ 93,  84,  63],
       [ 42,  48,  23],
       [119, 117,  79]])

# Valores propios (*Eigenvalues*)

In [193]:
np.linalg.eig(A)

(array([13.21221617,  0.55634832, -1.76856449]),
 array([[-0.53726088, -0.56614907,  0.44962939],
        [-0.36299392,  0.45455591, -0.8697971 ],
        [-0.76130556,  0.68764392,  0.2031906 ]]))

# Determinante

In [194]:
np.linalg.det(A)

-12.99999999999999

In [195]:
np.linalg.det(B)

-254.99999999999991

# Inversa

In [196]:
A

array([[7, 5, 2],
       [4, 1, 3],
       [9, 6, 4]])

In [197]:
np.linalg.inv(A)

array([[ 1.07692308,  0.61538462, -1.        ],
       [-0.84615385, -0.76923077,  1.        ],
       [-1.15384615, -0.23076923,  1.        ]])

# Traspuesta

In [198]:
A.transpose()   # equivalente a A.T

array([[7, 4, 9],
       [5, 1, 6],
       [2, 3, 4]])

In [199]:
np.array_equal(A.transpose(), A.T)

True

# Elevar una matriz a una potencia

In [200]:
A

array([[7, 5, 2],
       [4, 1, 3],
       [9, 6, 4]])

$\mathcal{A}^3$:

In [201]:
np.linalg.matrix_power(A, 3)

array([[1150,  709,  478],
       [ 776,  472,  327],
       [1629, 1002,  679]])

# ¿Es eficiente?

In [202]:
big_matrix = np.random.randint(0, 1000, size=(100, 100))

Función recursiva para multiplicar matrices "a mano":

In [203]:
def custom_matrix_power(matrix, power):
    if power == 1:
        return matrix
    else:
        return np.dot(matrix, custom_matrix_power(matrix, power - 1))

In [204]:
%timeit custom_matrix_power(big_matrix, 25)

13.2 ms ± 281 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [205]:
%timeit np.linalg.matrix_power(big_matrix, 25)

3.83 ms ± 49.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


# Sistemas de ecuaciones lineales

$
\begin{cases}
    -x_1 + 2x_3 = 1\\
    x_1 - x_2 = -2\\
    x_2 + x_3 = -1
\end{cases}
\Longrightarrow
\begin{pmatrix}
    1 & 0 & 2 \\
    1 & -1 & 0 \\
    0 & 1 & 1
\end{pmatrix}
\begin{pmatrix}
    x_1 \\
    x_2 \\
    x_3
\end{pmatrix}=
\begin{pmatrix}
    1 \\
    -2 \\
    -1
\end{pmatrix}
\Longrightarrow
\mathcal{A} \mathcal{X} = \mathcal{B}
$

In [206]:
A = np.array([[1, 0, 2], [1, -1, 0], [0, 1, 1]])
A

array([[ 1,  0,  2],
       [ 1, -1,  0],
       [ 0,  1,  1]])

In [207]:
B = np.array([1, -2, -1]).reshape(-1, 1)
B

array([[ 1],
       [-2],
       [-1]])

In [208]:
np.linalg.solve(A, B)

array([[-7.],
       [-5.],
       [ 4.]])

La solución al sistema debe ser la misma que si calculamos:

$
\begin{align*}
    \mathcal{X} = \mathcal{A}^{-1} \mathcal{B}
\end{align*}
$

In [209]:
np.dot(np.linalg.inv(A), B)

array([[-7.],
       [-5.],
       [ 4.]])

## 💡Ejercicio

Dadas las matrices:

$
A=
\begin{bmatrix}
  1 & 2 \\
  1 & 4
\end{bmatrix}
;\
B=
\begin{bmatrix}
  -3 & 4 \\
  2 & 0
\end{bmatrix}
;\
C=
\begin{bmatrix}
  0 & -2 \\
  3 & 1
\end{bmatrix}
;\
D=
\begin{bmatrix}
  1 & -3 \\
  -1 & 2
\end{bmatrix}
$

, calcule:

- $A + B - C$
- $A - B + (C - D)$
- $2A - B$
- $A - 2B + 3C$
- $3(A + B) + \frac{1}{2}(B - C) + 2(A - C)$
- $A(B + C)$
- $AB + AC$
- $A(B + C (A+B))$

In [210]:
# Write your code here!

## ⭐️ Solución

In [211]:
# %load "solutions/numpy/matrix_arithmetics.py"

## 💡Ejercicio

Una matriz es *idempotente* si $A^2 = A$. Compruebe si las matrices siguientes lo son:

$
A=
\begin{bmatrix}
  25 & -20 \\
  30 & -24
\end{bmatrix}
;\
B=
\begin{bmatrix}
  4 & -3 \\
  2 & -1
\end{bmatrix}
;\
C=
\begin{bmatrix}
  3 & -1 \\
  6 & -2
\end{bmatrix}
$

In [212]:
# Write your code here!

## ⭐️ Solución

In [213]:
# %load "solutions/numpy/idempotent.py"

## 💡Ejercicio

Resuelva el siguiente sistema de ecuaciones:

$
\begin{cases}
    3x + 4y - z = 8\\
    5x - 2y + z = 4\\
    2x - 2y + z = 1
\end{cases}
$

In [214]:
# Write your code here!

## ⭐️ Solución

In [215]:
# %load "solutions/numpy/lineq.py"

## 💡Ejercicio

Compruebe que la matriz
$
\begin{bmatrix}
  1 & 2 \\
  3 & 5
\end{bmatrix}
$
satisface la ecuación matricial: $X^2 - 6X - I = 0$, donde $I$ es la matriz identidad de orden 2.

In [216]:
# Write your code here!

## ⭐️ Solución

In [217]:
# %load "solutions/numpy/identity_equation.py"

## 💡Ejercicio

Dadas las matrices:

$
A=
\begin{bmatrix}
  1 & -2 & 1 \\
  3 & 0 & 1
\end{bmatrix}
;\
B=
\begin{bmatrix}
  4 & 0 & -1 \\
  -2 & 1 & 0
\end{bmatrix}
$

, compruebe que se cumplen las siguientes igualdades:

- $(A + B)^t = A^t + B^t$
- $(3A)^t = 3A^t$

In [218]:
# Write your code here!

## ⭐️ Solución

In [219]:
# %load "solutions/numpy/transpose.py"

## 💡Ejercicio

Dada la matriz
$
A =
\begin{bmatrix}
  4 & 5 & -1 \\
  -3 & -4 & 1 \\
  -3 & -4 & 0
\end{bmatrix}
$
, calcule: $A^2, A^3, \dots, A^{128}$

¿Nota algo especial en los resultados?

In [220]:
# Write your code here!

## ⭐️ Solución

In [222]:
# %load "solutions/numpy/flip_powers.py"